### ISSUE TITLE
Dependency issue with bigwig_file 

### ISSUE THREAD

**Issue by mkroon1** [LUMC/vep2lovd#1]
I installed vep2lovd under python 2.7.12 using pip. But something appears to be missing in the bx-python dependency:

    Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
    [GCC 5.4.0 20160609] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import vep2lovd
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/mkroon/software/vep2lovd/vep2lovd/__init__.py", line 11, in <module>
        from .parser import LOVDFile
    File "/home/mkroon/software/vep2lovd/vep2lovd/parser.py", line 18, in <module>
        from .annotate import Annotator
    File "/home/mkroon/software/vep2lovd/vep2lovd/annotate.py", line 16, in <module>
        from bx.bbi.bigwig_file import BigWigFile
    ImportError: No module named bigwig_file

**Comment by sndrtj** [comment]
This is an unfortunate side-effect of `bx-python` monkey patching itself whenever it finds a `numpy` installation. We do list `numpy` as a dependency, but since `bx-python` does not, pip likely installed `bx-python` before `numpy`, which leads to the behaviour you've seen. The solution would be to install `numpy` _before_ anything else. 

I will add a section about this to the readme.

**Comment by mkroon1** [comment]
$ virtualenv vep2lovd_env
    New python executable in /home/mkroon/LOVD/development/gnomad_import/vep2lovd_env/bin/python
    Installing setuptools, pip, wheel...done.

    $ vep2lovd_env/bin/pip --version
    pip 9.0.1 from /home/mkroon/LOVD/development/gnomad_import/vep2lovd_env/local/lib/python2.7/site-packages (python 2.7)

    $ vep2lovd_env/bin/pip install numpy
    Collecting numpy
    Downloading numpy-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl (16.6MB)
        100% |████████████████████████████████| 16.6MB 92kB/s 
    Installing collected packages: numpy
    Successfully installed numpy-1.13.1

    $ vep2lovd_env/bin/pip install -e ~/software/vep2lovd/
    Obtaining file:///home/mkroon/software/vep2lovd
    Requirement already satisfied: numpy in ./vep2lovd_env/lib/python2.7/site-packages (from vep2lovd==0.1)
    Collecting pyvcf (from vep2lovd==0.1)
    Collecting hgvs==0.3.7 (from vep2lovd==0.1)
    Collecting pysam (from vep2lovd==0.1)
    Using cached pysam-0.11.2.2-cp27-cp27mu-manylinux1_x86_64.whl
    Collecting bx-python==0.7.1 (from vep2lovd==0.1)
    Collecting six (from vep2lovd==0.1)
    Using cached six-1.10.0-py2.py3-none-any.whl
    Requirement already satisfied: setuptools in ./vep2lovd_env/lib/python2.7/site-packages (from pyvcf->vep2lovd==0.1)
    Collecting bioutils>=0.0.6 (from hgvs==0.3.7->vep2lovd==0.1)
    Collecting biopython (from hgvs==0.3.7->vep2lovd==0.1)
    Using cached biopython-1.69.tar.gz
    Collecting psycopg2 (from hgvs==0.3.7->vep2lovd==0.1)
    Using cached psycopg2-2.7.1-cp27-cp27mu-manylinux1_x86_64.whl
    Collecting multifastadb (from hgvs==0.3.7->vep2lovd==0.1)
    Using cached multifastadb-0.2.10-py2.py3-none-any.whl
    Collecting requests>=1.0.0 (from hgvs==0.3.7->vep2lovd==0.1)
    Using cached requests-2.18.1-py2.py3-none-any.whl
    Collecting recordtype (from hgvs==0.3.7->vep2lovd==0.1)
    Collecting parsley (from hgvs==0.3.7->vep2lovd==0.1)
    Using cached Parsley-1.3-py2.py3-none-any.whl
    Collecting ordered-set (from multifastadb->hgvs==0.3.7->vep2lovd==0.1)
    Collecting idna<2.6,>=2.5 (from requests>=1.0.0->hgvs==0.3.7->vep2lovd==0.1)
    Using cached idna-2.5-py2.py3-none-any.whl
    Collecting urllib3<1.22,>=1.21.1 (from requests>=1.0.0->hgvs==0.3.7->vep2lovd==0.1)
    Using cached urllib3-1.21.1-py2.py3-none-any.whl
    Collecting chardet<3.1.0,>=3.0.2 (from requests>=1.0.0->hgvs==0.3.7->vep2lovd==0.1)
    Using cached chardet-3.0.4-py2.py3-none-any.whl
    Collecting certifi>=2017.4.17 (from requests>=1.0.0->hgvs==0.3.7->vep2lovd==0.1)
    Using cached certifi-2017.4.17-py2.py3-none-any.whl
    Building wheels for collected packages: biopython
    Running setup.py bdist_wheel for biopython ... done
    Stored in directory: /home/mkroon/.cache/pip/wheels/11/15/60/25711f23f903630be11f25fa6284e8ecb6a73b227ba9c9b799
    Successfully built biopython
    Installing collected packages: pyvcf, idna, urllib3, chardet, certifi, requests, six, bioutils, biopython, psycopg2, pysam, ordered-set, multifastadb, recordtype, parsley, hgvs, bx-python, vep2lovd
    Running setup.py develop for vep2lovd
    Successfully installed biopython-1.69 bioutils-0.2.6 bx-python-0.7.1 certifi-2017.4.17 chardet-3.0.4 hgvs-0.3.7 idna-2.5 multifastadb-0.2.10 ordered-set-2.0.2 parsley-1.3 psycopg2-2.7.1 pysam-0.11.2.2 pyvcf-0.6.8 recordtype-1.1 requests-2.18.1 six-1.10.0 urllib3-1.21.1 vep2lovd

    $ vep2lovd_env/bin/python
    Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
    [GCC 5.4.0 20160609] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import vep2lovd
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/mkroon/software/vep2lovd/vep2lovd/__init__.py", line 11, in <module>
        from .parser import LOVDFile
    File "/home/mkroon/software/vep2lovd/vep2lovd/parser.py", line 18, in <module>
        from .annotate import Annotator
    File "/home/mkroon/software/vep2lovd/vep2lovd/annotate.py", line 16, in <module>
        from bx.bbi.bigwig_file import BigWigFile
    ImportError: No module named bigwig_file

**Comment by mkroon1** [comment]
Woops, hit comment before I was finished.

The commands above show that any messages I had regarding numpy earlier have dissapeared from the installation log due to installing numpy separately before. The issue still persists however.

**Comment by sndrtj** [comment]
Ugh.. pip is now using the cached version of bx-python, which does not have the correct c-extensions. I just encountered the same thing. It's already in the docs, but:

* uninstall bx-python
* `pip install --no-cache bx-python`

It should start compiling if it installs properly. 
Could you try this?

**Comment by mkroon1** [comment]
You're right. Somehow I assumed I got rid of the cache by destroying the virtualenv.

Anyway, it works now. Thanks, I'll close the issue.

**Comment by sndrtj** [comment]
Great! It may be a good idea to start looking for a bx-python replacement, because install issues like these are not nice. See #2
